steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyASKb9Bh9bfyt8DC53Z3zc8SqmTsy62Gss'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=synapse-edge-5322a.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=synapse-edge-5322a'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=synapse-edge-5322a.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=595062003787'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:595062003787:web:ae52c3c6b9f5ee595755ce'
      - '-f'
      - './Dockerfile'
      - '.'
    dir: 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--platform=managed'
      - '--image=${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=${_DEPLOY_REGION}'
    entrypoint: gcloud

images:
  - '${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

substitutions:
  _AR_HOSTNAME: asia-south1-docker.pkg.dev
  _DEPLOY_REGION: asia-south1
  _REPO_NAME: synapse-edge
  _SERVICE_NAME: synapse-edge

options:
  logging: CLOUD_LOGGING_ONLY
